### ISSUE TITLE
How to determine a fixed threshold for Line Level Localization?

### ISSUE THREAD

**Issue by scrambled-egg-py** [awsm-research/LineVul#1]
Hi Authors,
I was going through the code for Line Level localization for `reasoning_method=attention` and according to line 998 of linevul_main.py, scores of all lines in a function are calculated and sorted from high to low. After which it checked whether the flaw lines were in top10 predicted (with `top_k_constant=10`) or similar technique using `top_k_loc`.
Is there any way to identify a threshold, above which we can classify Lines as Vulnerable for examples predicted as Vulnerable, Like an inference Pipeline in which we enter a function and it outputs classification (vuln or not) and index of lines containing vulnerability (if classified as vulnerable).
Thanks for sharing the code with the community.

**Comment by MichaelFu1998-create** [comment]
Hi @scrambled-egg-py ,
Such threshold implementation is possible, for example, you may normalize the line score into 0-1 and determine a threshold, e.g. 0.7, any line above 0.7 will be treated as vulnerable line. Make use of sigmoid or softmax activation is also possible to normalize attention score. However, such approach is out of scope of LineVul paper. Hope this help 😁 

Michael

**Comment by MichaelFu1998-create** [comment]
feel free to open a new issue if still having any questions
