### ISSUE TITLE
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format( RuntimeError: Error(s) in loading state_dict for Model:         Unexpected key(s) in state_dict: "roberta.embeddings.position_ids", "encoder.roberta.embeddings.position_ids". 

### ISSUE THREAD

**Issue by 3481554467** [awsm-research/LineVul#11]
How can I handle this error when I only use the downloaded model for inference?

Traceback (most recent call last):
  File "linevul_main.py", line 1253, in <module>
    main()
  File "linevul_main.py", line 1246, in main
    model.load_state_dict(torch.load(output_dir, map_location=args.device))
  File "/home/xxx/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Model:
        Unexpected key(s) in state_dict: "roberta.embeddings.position_ids", "encoder.roberta.embeddings.position_ids".

**Comment by MichaelFu1998-create** [comment]
Hi @3481554467,
I've updated a statement in `./linevul/linevul_main.py`
Please clone the repo again and see if it works now.
Thank you!

**Comment by 3481554467** [comment]
> Hi @3481554467, I've updated a statement in `./linevul/linevul_main.py` Please clone the repo again and see if it works now. Thank you!

Thanks!I`ll try it again,hava a good day!

**Comment by 3481554467** [comment]
> Hi @3481554467, I've updated a statement in `./linevul/linevul_main.py` Please clone the repo again and see if it works now. Thank you!

It works~!Thanks @MichaelFu1998-create ，you are a responsible researcher, and your papers are excellent.
