### ISSUE TITLE
An Error happened when I tried to replicate RQ1.

### ISSUE THREAD

**Issue by Chang-jian** [awsm-research/LineVul#14]
I had set up the enviroment and downloaded the csv files. Then I tried to replicate RQ1.
I ran this code:
`python linevul_main.py`
Some errors occured:
HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/None/resolve/main/config.json
...
Repository Not Found for url: https://huggingface.co/None/resolve/main/config.json.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.
Invalid username or password.
...
OSError: None is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` o by passing `token=<your_token>` 
It seems like that the url "huggingface.co/None/resolve/main/config.json" is a wrong address. The "None" should be something else.  What can I do to deal with this? I'd appreciate it if you can teach me how to solve this problem:)

**Comment by MichaelFu1998-create** [comment]
Hello @Chang-jian 
Sorry for the late response as I'm traveling for a conference.
To replicate RQ1 please run the python file with required arguments specified.

To replicate RQ1 results with the downloaded model, run:

python linevul_main.py \
  --model_name=12heads_linevul_model.bin \
  --output_dir=./saved_models \
  --model_type=roberta \
  --tokenizer_name=microsoft/codebert-base \
  --model_name_or_path=microsoft/codebert-base \
  --do_test \
  --train_data_file=../data/big-vul_dataset/train.csv \
  --eval_data_file=../data/big-vul_dataset/val.csv \
  --test_data_file=../data/big-vul_dataset/test.csv \
  --block_size 512 \
  --eval_batch_size 512

To replicate RQ1 from training, run:

python linevul_main.py \
  --output_dir=./saved_models \
  --model_type=roberta \
  --tokenizer_name=microsoft/codebert-base \
  --model_name_or_path=microsoft/codebert-base \
  --do_train \
  --do_test \
  --train_data_file=../data/big-vul_dataset/train.csv \
  --eval_data_file=../data/big-vul_dataset/val.csv \
  --test_data_file=../data/big-vul_dataset/test.csv \
  --epochs 10 \
  --block_size 512 \
  --train_batch_size 16 \
  --eval_batch_size 16 \
  --learning_rate 2e-5 \
  --max_grad_norm 1.0 \
  --evaluate_during_training \
  --seed 123456  2>&1 | tee train.log

If still having any questions, feel free to leave further comments. I'm happy to help.

**Comment by Chang-jian** [comment]
It works！ Thank you very much！
