### ISSUE TITLE
Question about "Predict Real-World Software Vulnerabilities"

### ISSUE THREAD

**Issue by delta507** [awsm-research/LineVul#2]
You evaluate the model on dataset  of "Top-25 Most Dangerous CWEs in 2021".  I want to know how you choose the real-world dataset for each CWE type ？

**Comment by MichaelFu1998-create** [comment]
Hi @delta507,
We evaluate our approach using the Big-Vul dataset.
https://github.com/ZeoVan/MSR_20_Code_vulnerability_CSV_Dataset

The top-25 measurement uses the subset of our testing data where non top-25 CWEs were filtered.

**Comment by delta507** [comment]
I see, thanks for your answer!
