### ISSUE TITLE
Question about “WordlevelPretrainedBERT.bin”

### ISSUE THREAD

**Issue by YangJiahui0608** [awsm-research/LineVul#3]
"https://drive.google.com/uc?id=1cXeaWeBCpBuY6gPkRft2tS7SnDZrBed-"
The download address appears to be wrong. I click in to show that the address does not exist. 
Could you please check it out？ Thanks.

**Comment by MichaelFu1998-create** [comment]
Hi @YangJiahui0608,
The link should work now.
