### ISSUE TITLE
How to test the pre-trained model without retraining

### ISSUE THREAD

**Issue by ahmedihabb2** [awsm-research/LineVul#4]
How to test the pre-trained model without retraining, as I used this [command](https://github.com/awsm-research/LineVul#:~:text=To%20reproduce%20the%20RQ1%20result%2C%20run%20the%20following%20commands%20(Inference%20only)%3A) 
and it seems that it started the training again

**Comment by MichaelFu1998-create** [comment]
Hi @ahmedihabb2, if the "do_train" argument is not passed, then it won't start training.
I tested the command you used, and it started testing the pre-trained model w/o retraining.
