### ISSUE TITLE
How to handle with extremly long code sections?

### ISSUE THREAD

**Issue by Vela-zz** [awsm-research/LineVul#7]
Hi, I now want to train a new tokenizer for my on-premise C/C++ dataset, but I found some extremely long code section that is hard to handle. I check some Papers like LineVul, can you tell me how to preprocess these extremely long code sections? I only find some code from codeXGLUE that takes first BLCOK_SIZE - 2 tokens, is this method can embed the extremely long code into a right/nearly right position in latent space ?

**Comment by MichaelFu1998-create** [comment]
Hi @Vela-zz 
To train a new tokenizer, you may consider outputting all of your code from your C/C++ data set to a single .txt file.
Then you can use the tokenizer lib to train your tokenizer with the prepared .txt file.
The following code snippet is an example of training a BPE tokenizer with a prepared .txt file:

```
from tokenizers import ByteLevelBPETokenizer

special_tokens = ["<s>",
                  "<pad>",
                  "</s>",
                  "<unk>"]
tokenizer = ByteLevelBPETokenizer()
tokenizer.train(files="./all_code.txt", 
                vocab_size=32100, 
                min_frequency=2,
                show_progress=True,
                special_tokens=special_tokens)

# Save files to disk
tokenizer.save_model(".", "")
tokenizer.save('config.json')
```

**Comment by Vela-zz** [comment]
@MichaelFu1998-create  
Thanks for you Reply! 

Another Thing I want to know is how to deal with complex function sample that include 1000+ (Max 10000+) tokens, I notice that there are also some complex functions have 3000+ tokens after tokenization in line-big-vul train dataset. Dose Line-Vul just use first BLOCK_SIZE tokens of complex function samples to train model ?

**Comment by Vela-zz** [comment]
Thanks!
