### ISSUE TITLE
CodeSearchNet BPE tokenizer

### ISSUE THREAD

**Issue by jeffyjeff2893** [awsm-research/LineVul#9]
How can I retrain the linevul model approach with the pretrained bpe tokenizer as stated in the paper and where can I find the pretrained tokenizer?

**Comment by MichaelFu1998-create** [comment]
Hi @jeffyjeff2893,
You can load the tokenizer pre-trained on CodeSearchNet:
```
from transformers import RobertaTokenizer
tokenizer = RobertaTokenizer.from_pretrained("microsoft/codebert-base")
```

I quote this code snippet, https://github.com/awsm-research/LineVul/issues/7#issuecomment-1567767396, in case you wish to retrain the tokenizer

**Comment by jeffyjeff2893** [comment]
Great, thanks
